package net.jajica.libiot;

public enum CONFIGURACION_CONEXION_MQTT {
    
    CONFIGURACION_MQTT_OK,
    CONFIGURACION_MQTT_INEXISTENTE,
    CONFIGURACION_MQTT_CORRUPTA,
    CONFIGURACION_MQTT_DEFECTO_ERRONEA,
    CONFIGURACION_MQTT_ERROR_ESCRIBIR_CONFIGURACION

}
