package net.jajica.libiot;

public enum MQTT_STATE_CONNECTION {
    CONEXION_MQTT_CON_EXITO,
    CONEXION_MQTT_COMPLETA,
    CONEXION_MQTT_DESCONECTADA,
    CONEXION_MQTT_FAIL,
    CONEXION_MQTT_LOST,
    CONEXION_MQTT_ACTIVE,
    CONEXION_MQTT_PENDIENTE,
    CONEXION_MQTT_ERROR_CONNECT,
    CONEXION_MQTT_ERROR_ALGORITMO_CERTIIFICADO,
    CONEXION_MQTT_ERROR_IO,
    CONEXION_MQTT_ERROR_KEY_MANAGEMENT,
    CONEXION_MQTT_ERROR_CERTIFICATE,
    CONEXION_MQTT_ERROR_IRRECUPERABLE,
    CONEXION_MQTT_ERROR_SUSCRIPCION_TOPIC;

}
